<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tier1 = \App\Models\CpmTier::where('name', 'Tier 1')->first();
        $tier2 = \App\Models\CpmTier::where('name', 'Tier 2')->first();
        $tier3 = \App\Models\CpmTier::where('name', 'Tier 3')->first();
        $defaultTier = \App\Models\CpmTier::where('name', 'Default')->first();

        $countries = [
            ['name' => 'United States of America', 'iso_code' => 'US', 'cpm_tier_id' => $tier1->id ?? null],
            ['name' => 'Canada', 'iso_code' => 'CA', 'cpm_tier_id' => $tier1->id ?? null],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'cpm_tier_id' => $tier1->id ?? null],
            ['name' => 'Australia', 'iso_code' => 'AU', 'cpm_tier_id' => $tier1->id ?? null],
            ['name' => 'Germany', 'iso_code' => 'DE', 'cpm_tier_id' => $tier2->id ?? null],
            ['name' => 'France', 'iso_code' => 'FR', 'cpm_tier_id' => $tier2->id ?? null],
            ['name' => 'Japan', 'iso_code' => 'JP', 'cpm_tier_id' => $tier2->id ?? null],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'cpm_tier_id' => $tier3->id ?? null],
            ['name' => 'India', 'iso_code' => 'IN', 'cpm_tier_id' => $tier3->id ?? null],
            ['name' => 'China', 'iso_code' => 'CN', 'cpm_tier_id' => $tier3->id ?? null],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'cpm_tier_id' => $tier3->id ?? null],
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Albania', 'iso_code' => 'AL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Angola', 'iso_code' => 'AO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'AG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Austria', 'iso_code' => 'AT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Brunei Darussalam', 'iso_code' => 'BN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Cabo Verde', 'iso_code' => 'CV', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Central African Republic', 'iso_code' => 'CF', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Chad', 'iso_code' => 'TD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Chile', 'iso_code' => 'CL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Comoros', 'iso_code' => 'KM', 'cpm_tier_id' => $defaultTier->id ?? null], // ISO code düzeltildi
            ['name' => 'Congo', 'iso_code' => 'CG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Côte d\'Ivoire', 'iso_code' => 'CI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Czechia', 'iso_code' => 'CZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Democratic Republic of the Congo', 'iso_code' => 'CD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GQ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Eswatini', 'iso_code' => 'SZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Fiji', 'iso_code' => 'FJ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Finland', 'iso_code' => 'FI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Greece', 'iso_code' => 'GR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Iran', 'iso_code' => 'IR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Israel', 'iso_code' => 'IL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Italy', 'iso_code' => 'IT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Lao People\'s Democratic Republic', 'iso_code' => 'LA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Lesotho', 'iso_code' => 'LS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Libya', 'iso_code' => 'LY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Maldives', 'iso_code' => 'MV', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mali', 'iso_code' => 'ML', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Malta', 'iso_code' => 'MT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Marshall Islands', 'iso_code' => 'MH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Myanmar', 'iso_code' => 'MM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Niger', 'iso_code' => 'NE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'North Korea', 'iso_code' => 'KP', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'North Macedonia', 'iso_code' => 'MK', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Norway', 'iso_code' => 'NO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Oman', 'iso_code' => 'OM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Palau', 'iso_code' => 'PW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Panama', 'iso_code' => 'PA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Peru', 'iso_code' => 'PE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Poland', 'iso_code' => 'PL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Republic of Korea', 'iso_code' => 'KR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Republic of Moldova', 'iso_code' => 'MD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Romania', 'iso_code' => 'RO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Russian Federation', 'iso_code' => 'RU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Saint Lucia', 'iso_code' => 'LC', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'ST', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Spain', 'iso_code' => 'ES', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Syrian Arab Republic', 'iso_code' => 'SY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Timor-Leste', 'iso_code' => 'TL', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Togo', 'iso_code' => 'TG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'United Republic of Tanzania', 'iso_code' => 'TZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Viet Nam', 'iso_code' => 'VN', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'cpm_tier_id' => $defaultTier->id ?? null],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'cpm_tier_id' => $defaultTier->id ?? null],
        ];

        foreach ($countries as $countryData) {
            \App\Models\Country::firstOrCreate(
                ['iso_code' => $countryData['iso_code']],
                $countryData
            );
        }
    }
}
