import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: ['intro', 'quick-start', 'getting-started', 'dashboard'],
      collapsed: false,
    },
    {
      type: 'category',
      label: '💰 Monetization',
      items: ['earnings', 'withdrawals', 'referrals'],
    },
    {
      type: 'category',
      label: '📊 Analytics & Reports',
      items: ['analytics'],
    },
    {
      type: 'category',
      label: '🛠️ Tools',
      items: [
        'api',
        {
          type: 'autogenerated',
          dirName: 'tools',
        },
      ],
    },
    {
      type: 'category',
      label: '🎮 Gamification',
      items: [
        'gamification',
        {
          type: 'autogenerated',
          dirName: 'gamification',
        },
      ],
    },
    {
      type: 'category',
      label: '📢 Advertising',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advertising',
        },
      ],
    },
    {
      type: 'category',
      label: '🔐 Account & Security',
      items: [
        {
          type: 'autogenerated',
          dirName: 'account',
        },
      ],
    },
    {
      type: 'category',
      label: '❓ Help',
      items: ['faq', 'troubleshooting'],
    },
  ],
};

export default sidebars;
